---
swagger: "2.0"
info:
  description: "AI Photo Search application, built during the Cloud and Big Data course\
    \ at Columbia University."
  version: "1.0.0"
  title: "Photo Search"
host: "bsuufvf9n2.execute-api.us-east-1.amazonaws.com"
basePath: "/s3"
schemes:
- "https"
paths:
  /search:
    get:
      operationId: "searchPhotos"
      produces:
      - "application/json"
      parameters:
      - name: "q"
        in: "query"
        required: false
        type: "string"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/SearchResponse"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "500":
          description: "500 response"
          schema:
            $ref: "#/definitions/Error"
        "403":
          description: "403 response"
          schema:
            $ref: "#/definitions/Error"
      security:
      - api_key: []
    options:
      consumes:
      - "application/json"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /upload/{bucket}/{key}:
    put:
      produces:
      - "application/json"
      parameters:
      - name: "key"
        in: "path"
        required: true
        type: "string"
      - name: "bucket"
        in: "path"
        required: true
        type: "string"
      - name: "x-amz-meta-customLabels"
        in: "header"
        required: false
        type: "string"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/MODEL95d364"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
        "500":
          description: "500 response"
          schema:
            $ref: "#/definitions/Error"
        "403":
          description: "403 response"
          schema:
            $ref: "#/definitions/Error"
      security:
      - api_key: []
    options:
      consumes:
      - "application/json"
      parameters:
      - name: "key"
        in: "path"
        required: true
        type: "string"
      - name: "bucket"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "x-api-key"
    in: "header"
definitions:
  Error:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      message:
        type: "string"
  Photo:
    type: "object"
    properties:
      url:
        type: "string"
      labels:
        type: "array"
        items:
          type: "string"
  MODEL95d364:
    type: "object"
  SearchResponse:
    type: "object"
    properties:
      results:
        type: "array"
        items:
          $ref: "#/definitions/Photo"
